//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by WLRClient.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_WLRCLIENT_DIALOG            102
#define IDR_MAINFRAME                   128
#define IDD_TAB_NEW_INF                 129
#define IDD_TAB_MY_INF                  130
#define IDD_TAB_CUSTOM_INF              131
#define IDD_TAB_SPECIAL_LINE            132
#define IDD_SEARCH_SELECT               133
#define IDD_SEARCH_GOODS                134
#define IDD_SEARCH_BULKGOODS            135
#define IDD_SEARCH_CARS                 136
#define IDD_SEARCH_SPECIAL              137
#define IDD_SEND_PHONEMSG               138
#define IDR_MENU_OPERATION              139
#define IDB_MAINPAGE                    141
#define IDD_VALUE_ADDED_SERVICE         142
#define IDD_EMBEDDED_IE                 143
#define IDD_POP_NOTICE                  146
#define IDB_GOODS                       147
#define IDB_BULKGOODS                   148
#define IDB_CARS                        149
#define IDB_SPECIAL                     150
#define IDB_SEARCH                      151
#define IDB_QUICKPUB                    152
#define IDB_SYSSETTING                  153
#define IDB_ADDVALUED                   154
#define IDB_AUTOREFRESH                 155
#define IDB_SHOWPHONE                   156
#define IDB_PREVPAGE                    157
#define IDB_BITMAP2                     158
#define IDB_NEXTPAGE                    158
#define IDB_NOTICE                      159
#define IDD_CONFIG_SET                  160
#define IDB_LOGINBKPIC                  160
#define IDD_PUB_GOODS                   161
#define IDD_CAMERA                      162
#define IDB_BITMAP1                     163
#define IDB_CHAT                        163
#define IDD_PUB_SELECT                  164
#define IDD_PUB_BULKGOODS               165
#define IDD_PUB_CARS                    166
#define IDD_PUB_SPECIAL                 167
#define IDD_ADD_CUSTOM_ZONE             168
#define IDD_USER_LOGIN                  169
#define IDD_PROGRESS                    170
#define IDB_SERVER                      171
#define IDB_WLR                         172
#define IDD_SERVICE                     173
#define IDD_MSG                         174
#define IDB_CENTER                      175
#define IDB_BITMAP3                     176
#define IDD_USERCENTER                  177
#define IDR_WAIT                        178
#define IDD_DLGWEB                      186
#define IDB_NOREFRESH                   188
#define IDB_NOSHOWPHONE                 189
#define IDB_RELEASE_GOODS               191
#define IDB_RELEASE_TRUCK_INFO          192
#define IDB_RELEASE_SPECIAL_LINE        193
#define IDB_MY_ACCOUNTANT               194
#define IDB_SHOPPING_MALL               195
#define IDB_GPS_LOCATING                196
#define IDB_MY_APP                      197
#define IDB_LOGIN                       207
#define IDB_LOGIN_CANCEL                208
#define IDB_BITMAP9                     209
#define IDB_LOGIN_CLOSE                 209
#define IDB_TAKE_PHOTO                  210
#define IDB_GOODS_SEARCH                212
#define IDB_NEW_INFO_TABLE              213
#define IDB_LOCAL                       214
#define IDB_STOP_REFRESH                215
#define IDB_SECRECY                     216
#define IDB_CANCEL                      217
#define IDB_MAIN_ICON                   221
#define IDB_LOGIN_BACKGROUND            225
#define IDC_BTN_MainPage                1000
#define IDC_COLOR_NAME                  1000
#define IDC_CONFIG_SET_SYSBKCLR         1000
#define IDC_BTN_TakePhoto               1000
#define IDC_BTN_Goods                   1001
#define IDC_COLOR_DETAIL                1001
#define IDC_CONFIG_SET_GRIDCLR          1001
#define IDC_COLOR_BG1                   1002
#define IDC_CONFIG_SET_ODDBKCLR         1002
#define IDC_BTN_Goods2                  1002
#define IDC_BTN_ReleaseGoods            1002
#define IDC_BTN_Cars                    1003
#define IDC_COLOR_BG2                   1003
#define IDC_CONFIG_SET_EVENBKCLR        1003
#define IDC_BTN_Line                    1004
#define IDC_FONT_SIZE                   1004
#define IDC_CONFIG_SET_ODDFGCLR         1004
#define IDC_BTN_Search                  1005
#define IDC_PUB_GOODS_STPROVINCE        1005
#define IDC_CONFIG_SET_EVENFGCLR        1005
#define IDC_BTN_Setting                 1006
#define IDC_PUB_GOODS_STCITY            1006
#define IDC_BTN_AutoUpdate              1007
#define IDC_PUB_GOODS_STCOUNTY          1007
#define IDC_BTN_PayService              1008
#define IDC_PUB_GOODS_ENPROVINCE        1008
#define IDC_BTN_HideTel                 1009
#define IDC_PUB_GOODS_ENCITY            1009
#define IDC_BTN_Pub                     1010
#define IDC_PUB_GOODS_ENCOUNTY          1010
#define IDC_TAB_Main                    1011
#define IDC_PUB_GOODS_IFYZDX            1011
#define IDC_PUB_GOODS_NAME              1012
#define IDC_BTN_SHOPPING_MALL           1012
#define IDC_PUB_GOODS_SYPROVINCE        1013
#define IDC_BTN_ReleaseTruckInfo        1013
#define IDC_TREE_Main                   1014
#define IDC_PUB_GOODS_SYCITY            1014
#define IDC_PUB_GOODS_LDGTIME           1015
#define IDC_BTN_ReleaseSpecialLine      1015
#define IDC_PUB_GOODS_WEIGHT            1016
#define IDC_BTN_MyAccountant            1016
#define IDC_TAB_NEW_INF_LIST            1017
#define IDC_PUB_GOODS_WEIGHTUNIT        1017
#define IDC_PUB_GOODS_CUBAGE            1017
#define IDC_BTN_GPS_LOCATING            1017
#define IDC_PUB_GOODS_PRICE             1018
#define IDC_BTN_MyAPP                   1018
#define IDC_BTN_MY_APP                  1018
#define IDC_PUB_GOODS_PRICEUNIT         1019
#define IDC_TAB_MY_INF_LIST             1020
#define IDC_PUB_GOODS_CARLENGTH         1020
#define IDC_TAB_CUSTOM_INF_LIST         1021
#define IDC_PUB_GOODS_CARTYPE           1021
#define IDC_TAB_SPECIAL_LINE_LIST       1022
#define IDC_PUB_GOODS_CARNUM            1022
#define IDC_SEARCH_SELECT_GOODS         1023
#define IDC_PUB_GOODS_TEL               1023
#define IDC_PUB_GOODS_TYPE              1024
#define IDC_START_PROVINCE              1025
#define IDC_PUB_GOODS_PREVIEW_BTN       1025
#define IDC_START_CITY                  1026
#define IDC_PUB_GOODS_PREVIEW_EDIT      1026
#define IDC_SEARCH_SELECT_BULKGOODS     1027
#define IDC_START_COUNTY                1027
#define IDC_PUB_GOODS_REPUBTYPE         1027
#define IDC_SEARCH_SELECT_CARS          1028
#define IDC_END_PROVINCE                1028
#define IDC_PUB_SELECT_GOODS            1028
#define IDC_PUB_GOODS_IFREMREPUB        1028
#define IDC_SEARCH_SELECT_SPECIAL       1029
#define IDC_END_CITY                    1029
#define IDC_PUB_SELECT_CARS             1029
#define IDC_PUB_GOODS_IFLONGTIME        1029
#define IDC_END_COUNTY                  1030
#define IDC_PUB_SELECT_BULKGOODS        1030
#define IDC_PUB_GOODS_IFUP              1030
#define IDC_CAR_LENGTH                  1031
#define IDC_PUB_SELECT_SPECIAL          1031
#define IDC_PUB_BULKGOODS_STPROVINCE    1031
#define IDC_CAR_TYPE                    1032
#define IDC_PUB_BULKGOODS_STCITY        1032
#define IDC_PUB_BULKGOODS_STCOUNTY      1033
#define IDC_PUB_BULKGOODS_ENPROVINCE    1034
#define IDC_PUB_BULKGOODS_ENCITY        1035
#define IDC_PUB_BULKGOODS_ENCOUNTY      1036
#define IDC_PUB_BULKGOODS_NAME          1037
#define IDC_PUB_BULKGOODS_WEIGHT        1038
#define IDC_PUB_BULKGOODS_WEIGHTUNIT    1039
#define IDC_PUB_BULKGOODS_CARTYPE       1040
#define IDC_PUB_BULKGOODS_TEL           1041
#define IDC_PUB_BULKGOODS_PREVIEW_EDIT  1042
#define IDC_PUB_BULKGOODS_PREVIEW_BTN   1043
#define IDC_PUB_BULKGOODS_SYPROVINCE    1044
#define IDC_PUB_BULKGOODS_SYCITY        1045
#define IDC_PUB_BULKGOODS_REPUBTYPE     1046
#define IDC_PUB_BULKGOODS_IFREMREPUB    1047
#define IDC_PUB_BULKGOODS_IFLONGTIME    1048
#define IDC_PUB_BULKGOODS_IFUP          1049
#define IDC_PUB_CARS_STPROVINCE         1050
#define IDC_PUB_CARS_STCITY             1051
#define IDC_PUB_CARS_STCOUNTY           1052
#define IDC_PUB_CARS_ENPROVINCE         1053
#define IDC_PUB_CARS_ENCITY             1054
#define IDC_PUB_CARS_ENCOUNTY           1055
#define IDC_PUB_CARS_CARLENGTH          1056
#define IDC_PUB_CARS_CARTYPE            1057
#define IDC_PUB_CARS_CARNUM             1058
#define IDC_PUB_CARS_NAME               1059
#define IDC_PUB_CARS_TYPE               1060
#define IDC_PUB_CARS_ENPROVINCE2        1061
#define IDC_PUB_CARS_WEIGHT             1062
#define IDC_PUB_CARS_CUBAGE             1063
#define IDC_PUB_CARS_ENCITY2            1064
#define IDC_PUB_CARS_ENCOUNTY2          1065
#define IDC_PUB_CARS_TEL                1066
#define IDC_PUB_CARS_PREVIEW_EDIT       1067
#define IDC_PUB_CARS_PREVIEW_BTN        1068
#define IDC_PUB_CARS_SYPROVINCE         1069
#define IDC_PUB_CARS_ENPROVINCE3        1069
#define IDC_PUB_CARS_SYCITY             1070
#define IDC_PUB_CARS_ENCITY3            1070
#define IDC_PUB_CARS_LDGTIME            1071
#define IDC_PUB_CARS_REPUBTYPE          1072
#define IDC_PUB_CARS_IFREMREPUB         1073
#define IDC_PUB_CARS_IFLONGTIME         1074
#define IDC_PUB_CARS_IFUP               1075
#define IDC_PUB_CARS_ENCOUNTY3          1075
#define IDC_PUB_SPECIAL_STPROVINCE      1076
#define IDC_PUB_SPECIAL_STCITY          1077
#define IDC_PUB_SPECIAL_STCOUNTY        1078
#define IDC_PUB_SPECIAL_ENPROVINCE      1079
#define IDC_PUB_SPECIAL_ENCITY          1080
#define IDC_PUB_SPECIAL_ENCOUNTY        1081
#define IDC_PUB_SPECIAL_WEIGHT_PRICE    1082
#define IDC_PUB_SPECIAL_LIGHT_PRICE     1083
#define IDC_PUB_SPECIAL_TYPE1           1084
#define IDC_PUB_SPECIAL_TYPE2           1085
#define IDC_PUB_SPECIAL_TRANSPORT1      1086
#define IDC_PUB_SPECIAL_TRANSPORT2      1087
#define IDC_PUB_SPECIAL_TIME1           1088
#define IDC_PUB_SPECIAL_TIME2           1089
#define IDC_PUB_SPECIAL_TIME3           1090
#define IDC_PUB_SPECIAL_TIME4           1091
#define IDC_PUB_SPECIAL_TIME5           1092
#define IDC_PUB_SPECIAL_INF             1093
#define IDC_PUB_SPECIAL_ST_NAME         1094
#define IDC_PUB_SPECIAL_ST_ADDRESS      1095
#define IDC_PUB_SPECIAL_ST_TEL          1096
#define IDC_PUB_SPECIAL_SEND            1097
#define IDC_PUB_SPECIAL_IFUP            1098
#define IDC_TAB_CUSTOM_COMB             1099
#define IDC_PUB_SPECIAL_EN_NAME         1100
#define IDC_TAB_CUSTOM_ADD              1100
#define IDC_PUB_SPECIAL_EN_ADDRESS      1101
#define IDC_TAB_CUSTOM_DELETE           1101
#define IDC_PUB_SPECIAL_TEL             1102
#define IDC_BUTTON1                     1102
#define IDC_TAB_CUSTOM_NEXT             1102
#define IDC_CONFIG_SET_ODDFONT          1102
#define IDC_VALUE_ADDED_SERVICE_IDCARD  1102
#define IDC_BTN_NOTICE                  1102
#define IDC_GetPic                      1102
#define IDC_BUTTON2                     1103
#define IDC_TAB_CUSTOM_PREV             1103
#define IDC_CONFIG_SET_EVENFONT         1103
#define IDC_VALUE_ADDED_SERVICE_REGISTRATION 1103
#define IDC_BTN_NOTICE2                 1103
#define IDC_BTN_CHAT                    1103
#define IDC_TAB_NEW_PREV                1104
#define IDC_VALUE_ADDED_SERVICE_DRIVINGLICENSE 1104
#define IDC_TAB_NEW_NEXT                1105
#define IDC_TAB_MY_PREV                 1106
#define IDC_TAB_MY_NEXT                 1107
#define IDC_TAB_SPECIAL_LINE_PREV       1108
#define IDC_TAB_SPECIAL_LINE_NEXT       1109
#define IDC_SEND_PHONEMSG_MSG           1110
#define IDC_SEND_PHONEMSG_PHONE         1111
#define IDC_USER_LOGIN_USERNAME         1112
#define IDC_USER_LOGIN_PASSWORD         1113
#define IDC_CONFIG_SET_ODDSTATIC        1113
#define IDC_CONFIG_SET_EVENSTATIC       1114
#define IDC_EMBEDDED_IE_BROWSER         1117
#define IDC_STATIC_AD                   1118
#define IDC_USER_LOGIN_REM_PASSNAME     1119
#define IDC_USER_LOGIN_REM_USERNAME     1120
#define ID_REGNEWUSER                   1121
#define IDC_PIC                         1122
#define ID_RETRIEVE_PASSWORD            1122
#define IDC_LIST1                       1123
#define IDC_PROGRESS1                   1124
#define IDC_BTN_WLR                     1125
#define IDC_BTN_SERVER                  1126
#define IDC_TREE1                       1127
#define IDC_EDIT1                       1128
#define IDC_FWZ                         1129
#define IDC_CEMTER                      1130
#define IDC_EXPLORER1                   1131
#define IDC_DATETIMEPICKER1             1132
#define IDC_CUSTOM1                     1133
#define IDC_SHOW                        1134
#define IDC_BUTTON3                     1135
#define IDC_DEFAULT                     1135
#define IDC_STATIC_SYS                  1137
#define IDC_STATIC_AG                   1139
#define IDC_EDID_START_ADDR             1142
#define IDC_BUTTON_LOCAL                1143
#define IDC_EDID_DEST_ADDR              1144
#define IDC_BUTTON_CLOSE                1144
#define IDC_BUTTON_CANCEL_SEARCH        1145
#define IDC_BUTTON_SECRECY              1146
#define IDC_BUTTON_STOP_REFRESH         1147
#define IDC_EDID_LINE_START_ADDR        1148
#define IDC_EDID_LINE_DEST_ADDR         1149
#define IDC_BUTTON_LINE_LOCAL           1150
#define IDC_BUTTON_LINE_CANCEL_SEARCH   1151
#define IDC_BUTTON_LINE_SECRECY         1152
#define IDC_BUTTON_LINE_STOP_REFRESH    1153
#define IDC_STATIC_START_ADDR           1154
#define IDC_STATIC_DEST_ADDR            1155
#define ID_32771                        32771
#define ID_MENU_SENDMSG_SENDMSG         32772
#define ID_32775                        32775
#define ID_MENU_OPERATION_SENDMSG       32776
#define ID_MENU_OPERATION_COLLECT       32777
#define ID_32778                        32778
#define ID_MENU_OPERATION_DELETE        32779
#define ID_32780                        32780
#define ID_MENU_OPERATION_DELFAV        32781

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        228
#define _APS_NEXT_COMMAND_VALUE         32783
#define _APS_NEXT_CONTROL_VALUE         1156
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
