//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by WLRClient.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_WLRCLIENT_DIALOG            102
#define IDR_MAINFRAME                   128
#define IDD_TAB_NEW_INF                 129
#define IDD_TAB_MY_INF                  130
#define IDD_TAB_CUSTOM_INF              131
#define IDD_TAB_SPECIAL_LINE            132
#define IDD_SEARCH_SELECT               133
#define IDD_SEARCH_GOODS                134
#define IDD_SEARCH_BULKGOODS            135
#define IDD_SEARCH_CARS                 136
#define IDD_SEARCH_SPECIAL              137
#define IDD_SEND_PHONEMSG               138
#define IDR_MENU_OPERATION              139
#define IDB_MAINPAGE                    141
#define IDD_VALUE_ADDED_SERVICE         142
#define IDD_EMBEDDED_IE                 143
#define IDD_POP_NOTICE                  146
#define IDB_GOODS                       147
#define IDB_BULKGOODS                   148
#define IDB_CARS                        149
#define IDB_SPECIAL                     150
#define IDB_SEARCH                      151
#define IDB_QUICKPUB                    152
#define IDB_SYSSETTING                  153
#define IDB_ADDVALUED                   154
#define IDB_AUTOREFRESH                 155
#define IDB_SHOWPHONE                   156
#define IDB_PREVPAGE                    157
#define IDB_BITMAP2                     158
#define IDB_NEXTPAGE                    158
#define IDB_NOTICE                      159
#define IDD_CONFIG_SET                  160
#define IDB_LOGINBKPIC                  160
#define IDD_PUB_GOODS                   161
#define IDD_CAMERA                      162
#define IDB_BITMAP1                     163
#define IDB_CHAT                        163
#define IDD_PUB_SELECT                  164
#define IDD_PUB_BULKGOODS               165
#define IDD_PUB_CARS                    166
#define IDD_PUB_SPECIAL                 167
#define IDD_ADD_CUSTOM_ZONE             168
#define IDD_USER_LOGIN                  169
#define IDD_PROGRESS                    170
#define IDB_SERVER                      171
#define IDB_WLR                         172
#define IDD_SERVICE                     173
#define IDD_MSG                         174
#define IDB_CENTER                      175
#define IDB_BITMAP3                     176
#define IDD_USERCENTER                  177
#define IDR_WAIT                        178
#define IDD_DLGWEB                      186
#define IDB_NOREFRESH                   188
#define IDB_NOSHOWPHONE                 189
#define IDB_RELEASE_GOODS               191
#define IDB_RELEASE_TRUCK_INFO          192
#define IDB_RELEASE_SPECIAL_LINE        193
#define IDB_MY_ACCOUNTANT               194
#define IDB_SHOPPING_MALL               195
#define IDB_GPS_LOCATING                196
#define IDB_MY_APP                      197
#define IDB_LOGIN                       207
#define IDB_LOGIN_CANCEL                208
#define IDB_BITMAP9                     209
#define IDB_LOGIN_CLOSE                 209
#define IDB_TAKE_PHOTO                  210
#define IDB_GOODS_SEARCH                212
#define IDB_NEW_INFO_TABLE              213
#define IDB_LOCAL                       214
#define IDB_SECRECY                     216
#define IDB_CANCEL                      217
#define IDB_MAIN_ICON                   221
#define IDB_LOGIN_BACKGROUND            225
#define IDD_PUB_WAY_ONE                 228
#define IDD_PUB_WAY_TWO                 230
#define IDD_DLG_SEARCH                  231
#define IDD_SEARCH_WAY_ONE              232
#define IDD_SEARCH_WAY_TWO              233
#define IDD_SEARCH_WAY_THREE            234
#define IDD_SEARCH_FAVORITE             235
#define IDD_DIALOG_PUB_HISTORY          236
#define IDD_DIALOG_NUMBER               237
#define IDD_DIALOG_CONTENT_LIST         238
#define IDD_DIALOG_ADDR_SEL             239
#define IDB_LAST_PAGE                   240
#define IDB_FIRST_PAGE                  241
#define IDB_BITMAP4                     242
#define IDB_BITMAP_COMMON_BTN           242
#define IDB_PUBLISH_THREE               243
#define IDB_PUBLISH_TWO                 244
#define IDB_PUBLISH_ONE                 245
#define IDB_STOP_REFRESH                247
#define IDB_HIDE_PHONE_NUM              249
#define IDD_SEARCH_FAV_RENAME           250
#define IDB_BITMAP5                     251
#define IDB_BITMAP6                     252
#define IDC_BTN_MainPage                1000
#define IDC_COLOR_NAME                  1000
#define IDC_CONFIG_SET_SYSBKCLR         1000
#define IDC_BTN_TakePhoto               1000
#define IDC_BTN_Goods                   1001
#define IDC_COLOR_DETAIL                1001
#define IDC_CONFIG_SET_GRIDCLR          1001
#define IDC_COLOR_BG1                   1002
#define IDC_CONFIG_SET_ODDBKCLR         1002
#define IDC_BTN_Goods2                  1002
#define IDC_BTN_ReleaseGoods            1002
#define IDC_BTN_Cars                    1003
#define IDC_COLOR_BG2                   1003
#define IDC_CONFIG_SET_EVENBKCLR        1003
#define IDC_BTN_Line                    1004
#define IDC_FONT_SIZE                   1004
#define IDC_CONFIG_SET_ODDFGCLR         1004
#define IDC_BTN_Search                  1005
#define IDC_PUB_GOODS_STPROVINCE        1005
#define IDC_CONFIG_SET_EVENFGCLR        1005
#define IDC_BTN_Setting                 1006
#define IDC_PUB_GOODS_STCITY            1006
#define IDC_BTN_AutoUpdate              1007
#define IDC_PUB_GOODS_STCOUNTY          1007
#define IDC_BTN_PayService              1008
#define IDC_PUB_GOODS_ENPROVINCE        1008
#define IDC_BTN_HideTel                 1009
#define IDC_PUB_GOODS_ENCITY            1009
#define IDC_BTN_Pub                     1010
#define IDC_PUB_GOODS_ENCOUNTY          1010
#define IDC_TAB_Main                    1011
#define IDC_PUB_GOODS_IFYZDX            1011
#define IDC_PUB_GOODS_NAME              1012
#define IDC_BTN_SHOPPING_MALL           1012
#define IDC_PUB_GOODS_SYPROVINCE        1013
#define IDC_BTN_ReleaseTruckInfo        1013
#define IDC_TREE_Main                   1014
#define IDC_PUB_GOODS_SYCITY            1014
#define IDC_PUB_GOODS_LDGTIME           1015
#define IDC_BTN_ReleaseSpecialLine      1015
#define IDC_PUB_GOODS_WEIGHT            1016
#define IDC_BTN_MyAccountant            1016
#define IDC_TAB_NEW_INF_LIST            1017
#define IDC_PUB_GOODS_WEIGHTUNIT        1017
#define IDC_PUB_GOODS_CUBAGE            1017
#define IDC_BTN_GPS_LOCATING            1017
#define IDC_PUB_GOODS_PRICE             1018
#define IDC_BTN_MyAPP                   1018
#define IDC_BTN_MY_APP                  1018
#define IDC_PUB_GOODS_PRICEUNIT         1019
#define IDC_TAB_MY_INF_LIST             1020
#define IDC_PUB_GOODS_CARLENGTH         1020
#define IDC_TAB_CUSTOM_INF_LIST         1021
#define IDC_PUB_GOODS_CARTYPE           1021
#define IDC_TAB_SPECIAL_LINE_LIST       1022
#define IDC_PUB_GOODS_CARNUM            1022
#define IDC_SEARCH_SELECT_GOODS         1023
#define IDC_PUB_GOODS_TEL               1023
#define IDC_PUB_GOODS_TYPE              1024
#define IDC_START_PROVINCE              1025
#define IDC_PUB_GOODS_PREVIEW_BTN       1025
#define IDC_START_CITY                  1026
#define IDC_PUB_GOODS_PREVIEW_EDIT      1026
#define IDC_SEARCH_SELECT_BULKGOODS     1027
#define IDC_START_COUNTY                1027
#define IDC_PUB_GOODS_REPUBTYPE         1027
#define IDC_SEARCH_SELECT_CARS          1028
#define IDC_END_PROVINCE                1028
#define IDC_PUB_SELECT_GOODS            1028
#define IDC_PUB_GOODS_IFREMREPUB        1028
#define IDC_SEARCH_SELECT_SPECIAL       1029
#define IDC_END_CITY                    1029
#define IDC_PUB_SELECT_CARS             1029
#define IDC_PUB_GOODS_IFLONGTIME        1029
#define IDC_END_COUNTY                  1030
#define IDC_PUB_SELECT_BULKGOODS        1030
#define IDC_PUB_GOODS_IFUP              1030
#define IDC_CAR_LENGTH                  1031
#define IDC_PUB_SELECT_SPECIAL          1031
#define IDC_PUB_BULKGOODS_STPROVINCE    1031
#define IDC_CAR_TYPE                    1032
#define IDC_PUB_BULKGOODS_STCITY        1032
#define IDC_PUB_BULKGOODS_STCOUNTY      1033
#define IDC_PUB_BULKGOODS_ENPROVINCE    1034
#define IDC_PUB_BULKGOODS_ENCITY        1035
#define IDC_PUB_BULKGOODS_ENCOUNTY      1036
#define IDC_PUB_BULKGOODS_NAME          1037
#define IDC_PUB_BULKGOODS_WEIGHT        1038
#define IDC_PUB_BULKGOODS_WEIGHTUNIT    1039
#define IDC_PUB_BULKGOODS_CARTYPE       1040
#define IDC_PUB_BULKGOODS_TEL           1041
#define IDC_PUB_BULKGOODS_PREVIEW_EDIT  1042
#define IDC_PUB_BULKGOODS_PREVIEW_BTN   1043
#define IDC_PUB_BULKGOODS_SYPROVINCE    1044
#define IDC_PUB_BULKGOODS_SYCITY        1045
#define IDC_PUB_BULKGOODS_REPUBTYPE     1046
#define IDC_PUB_BULKGOODS_IFREMREPUB    1047
#define IDC_PUB_BULKGOODS_IFLONGTIME    1048
#define IDC_PUB_BULKGOODS_IFUP          1049
#define IDC_PUB_CARS_STPROVINCE         1050
#define IDC_PUB_CARS_STCITY             1051
#define IDC_PUB_CARS_STCOUNTY           1052
#define IDC_PUB_CARS_ENPROVINCE         1053
#define IDC_PUB_CARS_ENCITY             1054
#define IDC_PUB_CARS_ENCOUNTY           1055
#define IDC_PUB_CARS_CARLENGTH          1056
#define IDC_PUB_CARS_CARTYPE            1057
#define IDC_PUB_CARS_CARNUM             1058
#define IDC_PUB_CARS_NAME               1059
#define IDC_PUB_CARS_TYPE               1060
#define IDC_PUB_CARS_ENPROVINCE2        1061
#define IDC_PUB_CARS_WEIGHT             1062
#define IDC_PUB_CARS_CUBAGE             1063
#define IDC_PUB_CARS_ENCITY2            1064
#define IDC_PUB_CARS_ENCOUNTY2          1065
#define IDC_PUB_CARS_TEL                1066
#define IDC_PUB_CARS_PREVIEW_EDIT       1067
#define IDC_PUB_CARS_PREVIEW_BTN        1068
#define IDC_PUB_CARS_SYPROVINCE         1069
#define IDC_PUB_CARS_ENPROVINCE3        1069
#define IDC_PUB_CARS_SYCITY             1070
#define IDC_PUB_CARS_ENCITY3            1070
#define IDC_PUB_CARS_LDGTIME            1071
#define IDC_PUB_CARS_REPUBTYPE          1072
#define IDC_PUB_CARS_IFREMREPUB         1073
#define IDC_PUB_CARS_IFLONGTIME         1074
#define IDC_PUB_CARS_IFUP               1075
#define IDC_PUB_CARS_ENCOUNTY3          1075
#define IDC_PUB_SPECIAL_STPROVINCE      1076
#define IDC_PUB_SPECIAL_STCITY          1077
#define IDC_PUB_SPECIAL_STCOUNTY        1078
#define IDC_PUB_SPECIAL_ENPROVINCE      1079
#define IDC_PUB_SPECIAL_ENCITY          1080
#define IDC_PUB_SPECIAL_ENCOUNTY        1081
#define IDC_PUB_SPECIAL_WEIGHT_PRICE    1082
#define IDC_PUB_SPECIAL_LIGHT_PRICE     1083
#define IDC_PUB_SPECIAL_TYPE1           1084
#define IDC_PUB_SPECIAL_TYPE2           1085
#define IDC_PUB_SPECIAL_TRANSPORT1      1086
#define IDC_PUB_SPECIAL_TRANSPORT2      1087
#define IDC_PUB_SPECIAL_TIME1           1088
#define IDC_PUB_SPECIAL_TIME2           1089
#define IDC_PUB_SPECIAL_TIME3           1090
#define IDC_PUB_SPECIAL_TIME4           1091
#define IDC_PUB_SPECIAL_TIME5           1092
#define IDC_PUB_SPECIAL_INF             1093
#define IDC_PUB_SPECIAL_ST_NAME         1094
#define IDC_PUB_SPECIAL_ST_ADDRESS      1095
#define IDC_PUB_SPECIAL_ST_TEL          1096
#define IDC_PUB_SPECIAL_SEND            1097
#define IDC_PUB_SPECIAL_IFUP            1098
#define IDC_TAB_CUSTOM_COMB             1099
#define IDC_PUB_SPECIAL_EN_NAME         1100
#define IDC_TAB_CUSTOM_ADD              1100
#define IDC_PUB_SPECIAL_EN_ADDRESS      1101
#define IDC_TAB_CUSTOM_DELETE           1101
#define IDC_PUB_SPECIAL_TEL             1102
#define IDC_BUTTON1                     1102
#define IDC_TAB_CUSTOM_NEXT             1102
#define IDC_CONFIG_SET_ODDFONT          1102
#define IDC_VALUE_ADDED_SERVICE_IDCARD  1102
#define IDC_BTN_NOTICE                  1102
#define IDC_GetPic                      1102
#define IDC_BUTTON2                     1103
#define IDC_TAB_CUSTOM_PREV             1103
#define IDC_CONFIG_SET_EVENFONT         1103
#define IDC_VALUE_ADDED_SERVICE_REGISTRATION 1103
#define IDC_BTN_NOTICE2                 1103
#define IDC_BTN_CHAT                    1103
#define IDC_BUTTON_W1_FROM_CITY         1103
#define IDC_BUTTON_SW1_CLEAN_ADDR       1103
#define IDC_BUTTON_SW2_ADD_ALL_CITY     1103
#define IDC_BUTTON_USE                  1103
#define IDC_BUTTON_AUTO_REPUB           1103
#define IDC_TAB_NEW_PREV                1104
#define IDC_VALUE_ADDED_SERVICE_DRIVINGLICENSE 1104
#define IDC_BUTTON_W1_FROM_COUNTY       1104
#define IDC_BUTTON_SW1_CLEAN_PUBLISHER  1104
#define IDC_BUTTON_SW2_ADD_ALL_COUNTY   1104
#define IDC_BUTTON_DEL                  1104
#define IDC_BUTTON_DELETE               1104
#define IDC_BUTTON_ALL_COUNTY           1104
#define IDC_TAB_NEW_NEXT                1105
#define IDC_BUTTON_W1_TO_PROVINCE       1105
#define IDC_BUTTON_SW1_CLEAN_PHONE_NUM  1105
#define IDC_BUTTON_SW2_DEL              1105
#define IDC_BUTTON_RENAME               1105
#define IDC_BUTTON_CANCEL               1105
#define IDC_TAB_MY_PREV                 1106
#define IDC_BUTTON_W1_TO_CITY           1106
#define IDC_BUTTON_SW2_CLEAN            1106
#define IDC_TAB_NEW_UPTOP               1106
#define IDC_TAB_MY_NEXT                 1107
#define IDC_BUTTON_W1_TO_COUNTY         1107
#define IDC_BUTTON_SW2_ADD_KEY_WORD     1107
#define IDC_TAB_SPECIAL_LINE_PREV       1108
#define IDC_BUTTON_GOODS_NUM            1108
#define IDC_BUTTON_PUBLISH              1108
#define IDC_TAB_SPECIAL_LINE_NEXT       1109
#define IDC_BUTTON_CAR_NUM              1109
#define IDC_TAB_NEW_BOTTOM_DOWN         1109
#define IDC_SEND_PHONEMSG_MSG           1110
#define IDC_BUTTON_PRIACE_NUM           1110
#define IDC_SEND_PHONEMSG_PHONE         1111
#define IDC_BUTTON_SW3_CLEAN_KEY_WORD   1111
#define IDC_TAB_NEW_BOTTOM_DOWN2        1111
#define IDC_USER_LOGIN_USERNAME         1112
#define IDC_BUTTON_SW3_BACKSPACE        1112
#define IDC_USER_LOGIN_PASSWORD         1113
#define IDC_CONFIG_SET_ODDSTATIC        1113
#define IDC_CONFIG_SET_EVENSTATIC       1114
#define IDC_EMBEDDED_IE_BROWSER         1117
#define IDC_STATIC_AD                   1118
#define IDC_USER_LOGIN_REM_PASSNAME     1119
#define IDC_USER_LOGIN_REM_USERNAME     1120
#define ID_REGNEWUSER                   1121
#define IDC_PIC                         1122
#define ID_RETRIEVE_PASSWORD            1122
#define IDC_LIST1                       1123
#define IDC_PROGRESS1                   1124
#define IDC_LIST_SW2_TO_CITY            1124
#define IDC_LIST_CITY                   1124
#define IDC_BTN_WLR                     1125
#define IDC_LIST_SW2_TO_COUNTY          1125
#define IDC_LIST_COUNTY                 1125
#define IDC_BTN_SERVER                  1126
#define IDC_LIST_SW2_DEST_KEY_WORD      1126
#define IDC_TREE1                       1127
#define IDC_EDIT1                       1128
#define IDC_FWZ                         1129
#define IDC_CEMTER                      1130
#define IDC_EXPLORER1                   1131
#define IDC_DATETIMEPICKER1             1132
#define IDC_CUSTOM1                     1133
#define IDC_SHOW                        1134
#define IDC_BUTTON3                     1135
#define IDC_DEFAULT                     1135
#define IDC_BUTTON_PREVIEW              1135
#define IDC_BUTTON_SW1_ADDR             1135
#define IDC_BUTTON_PUB_WAY_ONE          1135
#define IDC_BUTTON_SW1_GOODS            1136
#define IDC_BUTTON_PUB_WAY_TWO          1136
#define IDC_STATIC_SYS                  1137
#define IDC_BUTTON_SW1_CAR_TYPE         1137
#define IDC_BUTTON_SEARCH               1137
#define IDC_BUTTON_SW1_CAR_SIZE         1138
#define IDC_BUTTON_HIDE_PHONE           1138
#define IDC_STATIC_AG                   1139
#define IDC_BUTTON_SW1_GOODS_TYPE       1139
#define IDC_BUTTON_SW3_GOODS            1140
#define IDC_BUTTON_SW3_CAR_TYPE         1141
#define IDC_EDID_START_ADDR             1142
#define IDC_BUTTON_SW3_CAR_SIZE         1142
#define IDC_BUTTON_LOCAL                1143
#define IDC_EDID_DEST_ADDR              1144
#define IDC_BUTTON_CLOSE                1144
#define IDC_BUTTON_CANCEL_SEARCH        1145
#define IDC_BUTTON_SECRECY              1146
#define IDC_BUTTON_STOP_REFRESH         1147
#define IDC_EDID_LINE_START_ADDR        1148
#define IDC_BUTTON_HIDE_PHONE_NUM       1148
#define IDC_EDID_LINE_DEST_ADDR         1149
#define IDC_BUTTON_LINE_LOCAL           1150
#define IDC_BUTTON_LINE_CANCEL_SEARCH   1151
#define IDC_BUTTON_LINE_SECRECY         1152
#define IDC_BUTTON_LINE_STOP_REFRESH    1153
#define IDC_LIST_SW3_FROM_ADDR          1154
#define IDC_STATIC_SW3_DEST_ADDR        1155
#define IDC_COMBO_INFO_TYPE             1156
#define IDC_CHECK_CLOSE                 1157
#define IDC_LIST_GOODS                  1159
#define IDC_EDIT_GOODS_NUM              1160
#define IDC_COMBO_GOOD_UNIT             1161
#define IDC_BUTTON_W1_FROM_PROVINCE     1162
#define IDC_STATIC_GP_GOODS             1163
#define IDC_LIST_CAR_SIZE               1164
#define IDC_STATIC_GP_CAR               1165
#define IDC_EDIT_CAR_NUM                1166
#define IDC_COMBO_CAR_UNIT              1167
#define IDC_EDIT_PRICE_NUM              1168
#define IDC_LIST_PRIACE                 1169
#define IDC_EDIT_PW1_CONTACT_NAME       1170
#define IDC_CHECK_PW1_CONTACT_NAME      1171
#define IDC_EDIT_PW1_CONTACT_PHONE      1172
#define IDC_CHECK_PW1_CONTACT_PHONE     1173
#define IDC_EDIT_PW1_PREVIEW            1174
#define IDC_LIST_CAR_TYPE               1175
#define IDC_COMBO_PW1_LDGOODS_DT        1176
#define IDC_COMBO_PW1_REPUB_SETTING     1177
#define IDC_CHECK_PW1_REM_REPUB_SETTING 1178
#define IDC_CHECK_PW1_LONGTIME          1179
#define IDC_BUTTON_PW1_PUB              1181
#define IDC_BUTTON_PW1_CLEAN            1182
#define IDC_COMBO_PW1_INFO_TYPE         1184
#define IDC_CHECK_W1_CLOSE              1185
#define IDC_BUTTON_NUM_ONE              1186
#define IDC_BUTTON_NUM_TWO              1187
#define IDC_BUTTON_NUM_THREE            1188
#define IDC_BUTTON_NUM_FOUR             1189
#define IDC_BUTTON_NUM_FIVE             1190
#define IDC_BUTTON_NUM_SIX              1191
#define IDC_BUTTON_NUM_SEVEN            1192
#define IDC_BUTTON_NUM_EIGHT            1193
#define IDC_BUTTON_NUM_NINE             1194
#define IDC_BUTTON_NUM_D_ZERO           1195
#define IDC_BUTTON_NUM_PERIOD           1196
#define IDC_BUTTON_NUM_COMMA            1197
#define IDC_BUTTON_NUM_DOT              1198
#define IDC_BUTTON_NUM_SEMICOLON        1199
#define IDC_BUTTON_NUM_HYPHEN           1200
#define IDC_BUTTON_NUM_SLASH            1201
#define IDC_BUTTON_NUM_R_BRACKET        1202
#define IDC_BUTTON_NUM_ZERO             1203
#define IDC_BUTTON_NUM_ARROW            1204
#define IDC_BUTTON_JI                   1205
#define IDC_BUTTON_XU                   1206
#define IDC_BUTTON_YAO                  1207
#define IDC_BUTTON_QIU                  1208
#define IDC_BUTTON_FA                   1209
#define IDC_BUTTON_DAO                  1210
#define IDC_BUTTON_HUI                  1211
#define IDC_BUTTON_QU                   1212
#define IDC_BUTTON_CHE                  1213
#define IDC_BUTTON_DIAN                 1214
#define IDC_BUTTON_DUN                  1215
#define IDC_BUTTON_MI                   1216
#define IDC_BUTTON_YUAN                 1217
#define IDC_BUTTON_YUAN_DUN             1218
#define IDC_BUTTON_UNIT                 1219
#define IDC_BUTTON_BACKSPACE            1220
#define IDC_EDIT_PW2_CONTACT_NAME       1221
#define IDC_BUTTON_HUO                  1222
#define IDC_BUTTON_GOOD1                1223
#define IDC_BUTTON_GOOD2                1224
#define IDC_BUTTON_GOOD3                1225
#define IDC_BUTTON_CAR_SIZE             1226
#define IDC_BUTTON_CAR_TYPE             1227
#define IDC_BUTTON_PRICE                1228
#define IDC_BUTTON_PHRASE               1229
#define IDC_BUTTON_SPECIAL              1230
#define IDC_BUTTON_CHARACTER            1231
#define IDC_BUTTON_WORD                 1232
#define IDC_CHECK_PW2_CONTACT_NAME      1233
#define IDC_EDIT_PW2_PREVIEW            1234
#define IDC_COMBO_PW2_LDGOODS_DT        1235
#define IDC_COMBO_PW2_REPUB_SETTING     1236
#define IDC_CHECK_PW2_REM_REPUB_SETTING 1237
#define IDC_CHECK_PW2_LONGTIME          1238
#define IDC_BUTTON_PW2_PUB              1239
#define IDC_BUTTON_PW2_CLEAN            1240
#define IDC_BUTTON_PW2_CLOSE            1241
#define IDC_BUTTON_PW1_CLOSE            1242
#define IDC_CHECK_NO_FROM_ADDR          1243
#define IDC_TAB_SEARCH_WAY              1244
#define IDC_BUTTON_OK                   1247
#define IDC_BUTTON_CLEAN                1248
#define IDC_RADIO_SW1_ALL               1248
#define IDC_BUTTON_ADD_FAVORITE         1249
#define IDC_RADIO_SW1_GOODS             1249
#define IDC_BUTTON_SAVE                 1250
#define IDC_RADIO_SW1_CARS              1250
#define IDC_STATIC_FROM_ADDR            1251
#define IDC_STATIC_SW1_FROM_ADDR        1251
#define IDC_BUTTON_SW1_SELECT           1252
#define IDC_COMBO_SW1_KEY_WORD          1257
#define IDC_COMBO_SW1_PUBLISHER         1258
#define IDC_COMBO_SW1_PHONE_NUM         1259
#define IDC_RADIO_MATCH_ALL             1260
#define IDC_RADIO_MATCH_ANY             1261
#define IDC_COMBO_SW2_FROM_PROVINCE     1262
#define IDC_COMBO_SW2_FROM_CITY         1263
#define IDC_COMBO_SW2_FROM_COUNTY       1264
#define IDC_COMBO4                      1265
#define IDC_RADIO_SW2_ALL               1266
#define IDC_RADIO_SW2_GOODS             1267
#define IDC_RADIO_SW2_CARS              1268
#define IDC_LIST_SW2_TO_PROVINCE        1269
#define IDC_BUTTON_SW2_ADD_DEST         1270
#define IDC_RADIO_SW3_ALL               1271
#define IDC_RADIO_SW3_GOODS             1272
#define IDC_RADIO_SW3_CARS              1273
#define IDC_LIST_SW3_FROM_PROVINCE      1274
#define IDC_LIST_SW3_FROM_CITY          1275
#define IDC_LIST_SW3_FROM_COUNTY        1276
#define IDC_BUTTON_SW3_ADD_FROM         1277
#define IDC_BUTTON_SW3_ADD_FROM_ADDR    1277
#define IDC_BUTTON_SW3_ADD_ALL_CITY     1278
#define IDC_BUTTON_SW3_ADD_ALL_COUNTY   1279
#define IDC_BUTTON_SW3_DEL              1280
#define IDC_BUTTON_SW3_CLEAN            1281
#define IDC_COMBO_SW3_KEY_WORD          1282
#define IDC_BUTTON_SW3_ADDR             1283
#define IDC_BUTTON_SW3_GOODS_TYPE       1284
#define IDC_LIST_CTRL_SEARCH_FAVORITE   1285
#define IDC_BUTTON_REFRESH              1286
#define IDC_BUTTON_PW1_HISTORY          1287
#define IDC_BUTTON_PW2_HISTORY          1288
#define IDC_LIST_PUB_HISTORY            1289
#define IDC_BUTTON_MODIFY               1290
#define IDC_BUTTON_KB_NUM_SEVEN         1291
#define IDC_BUTTON_KB_NUM_EIGHT         1292
#define IDC_BUTTON_KB_NUM_NINE          1293
#define IDC_LIST_CONTENT                1293
#define IDC_BUTTON_KB_NUM_SEVEN4        1294
#define IDC_EDIT_PW1_FROM_PROVINCE      1294
#define IDC_BUTTON_KB_CLOSE             1294
#define IDC_BUTTON_KB_NUM_FOUR          1295
#define IDC_EDIT_PW1_FROM_CITY          1295
#define IDC_BUTTON_KB_NUM_FIVE          1296
#define IDC_EDIT_PW1_FROM_COUNTY        1296
#define IDC_BUTTON_KB_NUM_SIX           1297
#define IDC_EDIT_PW1_TO_PROVINCE        1297
#define IDC_BUTTON_KB_NUM_CLEAN         1298
#define IDC_EDIT_PW1_TO_CITY            1298
#define IDC_BUTTON_KB_NUM_ONE           1299
#define IDC_EDIT_PW1_TO_COUNTY          1299
#define IDC_BUTTON_KB_NUM_TWO           1300
#define IDC_EDIT_PW2_CONTACT_PHONE      1300
#define IDC_BUTTON_KB_NUM_THREE         1301
#define IDC_CHECK_PW2_CONTACT_PHONE     1301
#define IDC_BUTTON_KB_NUM_BACKSPACE     1302
#define IDC_BUTTON_PW1_FROM_PROVINCE    1302
#define IDC_BUTTON_KB_NUM_ZEOR1         1303
#define IDC_BUTTON_PW1_FROM_CITY        1303
#define IDC_BUTTON_KB_NUM_DOT           1304
#define IDC_BUTTON_PW1_FROM_COUNTY      1304
#define IDC_BUTTON_KB_NUM_ZERO2         1305
#define IDC_EDIT_DEST_ADDR              1305
#define IDC_BUTTON_KB_NUM_D_ZERO        1306
#define IDC_BUTTON_ALL_CITY             1306
#define IDC_LIST_PROVINCE               1307
#define IDC_STATIC_TITLE                1311
#define IDC_STATIC_CAR_UNIT             1312
#define IDC_EDIT_FAVORITE_NAME          1314
#define ID_32771                        32771
#define ID_MENU_SENDMSG_SENDMSG         32772
#define ID_32775                        32775
#define ID_MENU_OPERATION_SENDMSG       32776
#define ID_MENU_OPERATION_COLLECT       32777
#define ID_32778                        32778
#define ID_MENU_OPERATION_DELETE        32779
#define ID_32780                        32780
#define ID_MENU_OPERATION_DELFAV        32781

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        253
#define _APS_NEXT_COMMAND_VALUE         32783
#define _APS_NEXT_CONTROL_VALUE         1315
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
