/* soapFmpServiceImplServiceSoapBindingProxy.h
   Generated by gSOAP 2.7.17 from ./wsdl2h_generate/bz_560_service.h
   Copyright(C) 2000-2010, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapFmpServiceImplServiceSoapBindingProxy_H
#define soapFmpServiceImplServiceSoapBindingProxy_H
#include "soapH.h"
class FmpServiceImplServiceSoapBinding
{   public:
	/// Runtime engine context allocated in constructor
	struct soap *soap;
	/// Endpoint URL of service 'FmpServiceImplServiceSoapBinding' (change as needed)
	const char *endpoint;
	/// Constructor allocates soap engine context, sets default endpoint URL, and sets namespace mapping table
	FmpServiceImplServiceSoapBinding()
	{ soap = soap_new(); endpoint = "http://www.566560.com:8603/fmp/service/fmpserver"; if (soap && !soap->namespaces) { static const struct Namespace namespaces[] = 
{
	{"SOAP-ENV", "http://schemas.xmlsoap.org/soap/envelope/", "http://www.w3.org/*/soap-envelope", NULL},
	{"SOAP-ENC", "http://schemas.xmlsoap.org/soap/encoding/", "http://www.w3.org/*/soap-encoding", NULL},
	{"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
	{"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
	{"ns1", "http://impl.webservice.dot.com/", NULL, NULL},
	{"ns2", "http://webservice.dot.com/", NULL, NULL},
	{NULL, NULL, NULL, NULL}
};
	soap->namespaces = namespaces; } };
	/// Destructor frees deserialized data and soap engine context
	virtual ~FmpServiceImplServiceSoapBinding() { if (soap) { soap_destroy(soap); soap_end(soap); soap_free(soap); } };
	/// Invoke 'getNewBulkGoodsInf' of service 'FmpServiceImplServiceSoapBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getNewBulkGoodsInf(ns2__getNewBulkGoodsInf *ns2__getNewBulkGoodsInf_, ns2__getNewBulkGoodsInfResponse *ns2__getNewBulkGoodsInfResponse_) { return soap ? soap_call___ns1__getNewBulkGoodsInf(soap, endpoint, NULL, ns2__getNewBulkGoodsInf_, ns2__getNewBulkGoodsInfResponse_) : SOAP_EOM; };
	/// Invoke 'collectSpecialLine' of service 'FmpServiceImplServiceSoapBinding' and return error code (or SOAP_OK)
	virtual int __ns1__collectSpecialLine(ns2__collectSpecialLine *ns2__collectSpecialLine_, ns2__collectSpecialLineResponse *ns2__collectSpecialLineResponse_) { return soap ? soap_call___ns1__collectSpecialLine(soap, endpoint, NULL, ns2__collectSpecialLine_, ns2__collectSpecialLineResponse_) : SOAP_EOM; };
	/// Invoke 'getFavoriteSpecialLineInf' of service 'FmpServiceImplServiceSoapBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getFavoriteSpecialLineInf(ns2__getFavoriteSpecialLineInf *ns2__getFavoriteSpecialLineInf_, ns2__getFavoriteSpecialLineInfResponse *ns2__getFavoriteSpecialLineInfResponse_) { return soap ? soap_call___ns1__getFavoriteSpecialLineInf(soap, endpoint, NULL, ns2__getFavoriteSpecialLineInf_, ns2__getFavoriteSpecialLineInfResponse_) : SOAP_EOM; };
	/// Invoke 'getUserCustomInf' of service 'FmpServiceImplServiceSoapBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getUserCustomInf(ns2__getUserCustomInf *ns2__getUserCustomInf_, ns2__getUserCustomInfResponse *ns2__getUserCustomInfResponse_) { return soap ? soap_call___ns1__getUserCustomInf(soap, endpoint, NULL, ns2__getUserCustomInf_, ns2__getUserCustomInfResponse_) : SOAP_EOM; };
	/// Invoke 'getMyCarsInf' of service 'FmpServiceImplServiceSoapBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getMyCarsInf(ns2__getMyCarsInf *ns2__getMyCarsInf_, ns2__getMyCarsInfResponse *ns2__getMyCarsInfResponse_) { return soap ? soap_call___ns1__getMyCarsInf(soap, endpoint, NULL, ns2__getMyCarsInf_, ns2__getMyCarsInfResponse_) : SOAP_EOM; };
	/// Invoke 'getGoodsAndCarsInfNew' of service 'FmpServiceImplServiceSoapBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getGoodsAndCarsInfNew(ns2__getGoodsAndCarsInfNew *ns2__getGoodsAndCarsInfNew_, ns2__getGoodsAndCarsInfNewResponse *ns2__getGoodsAndCarsInfNewResponse_) { return soap ? soap_call___ns1__getGoodsAndCarsInfNew(soap, endpoint, NULL, ns2__getGoodsAndCarsInfNew_, ns2__getGoodsAndCarsInfNewResponse_) : SOAP_EOM; };
	/// Invoke 'sendPhoneMessage' of service 'FmpServiceImplServiceSoapBinding' and return error code (or SOAP_OK)
	virtual int __ns1__sendPhoneMessage(ns2__sendPhoneMessage *ns2__sendPhoneMessage_, ns2__sendPhoneMessageResponse *ns2__sendPhoneMessageResponse_) { return soap ? soap_call___ns1__sendPhoneMessage(soap, endpoint, NULL, ns2__sendPhoneMessage_, ns2__sendPhoneMessageResponse_) : SOAP_EOM; };
	/// Invoke 'setCarsStatus' of service 'FmpServiceImplServiceSoapBinding' and return error code (or SOAP_OK)
	virtual int __ns1__setCarsStatus(ns2__setCarsStatus *ns2__setCarsStatus_, ns2__setCarsStatusResponse *ns2__setCarsStatusResponse_) { return soap ? soap_call___ns1__setCarsStatus(soap, endpoint, NULL, ns2__setCarsStatus_, ns2__setCarsStatusResponse_) : SOAP_EOM; };
	/// Invoke 'getClickServiceStationInf' of service 'FmpServiceImplServiceSoapBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getClickServiceStationInf(ns2__getClickServiceStationInf *ns2__getClickServiceStationInf_, ns2__getClickServiceStationInfResponse *ns2__getClickServiceStationInfResponse_) { return soap ? soap_call___ns1__getClickServiceStationInf(soap, endpoint, NULL, ns2__getClickServiceStationInf_, ns2__getClickServiceStationInfResponse_) : SOAP_EOM; };
	/// Invoke 'getSearchSpecialLineInf' of service 'FmpServiceImplServiceSoapBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getSearchSpecialLineInf(ns2__getSearchSpecialLineInf *ns2__getSearchSpecialLineInf_, ns2__getSearchSpecialLineInfResponse *ns2__getSearchSpecialLineInfResponse_) { return soap ? soap_call___ns1__getSearchSpecialLineInf(soap, endpoint, NULL, ns2__getSearchSpecialLineInf_, ns2__getSearchSpecialLineInfResponse_) : SOAP_EOM; };
	/// Invoke 'getCustomCarsInf' of service 'FmpServiceImplServiceSoapBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getCustomCarsInf(ns2__getCustomCarsInf *ns2__getCustomCarsInf_, ns2__getCustomCarsInfResponse *ns2__getCustomCarsInfResponse_) { return soap ? soap_call___ns1__getCustomCarsInf(soap, endpoint, NULL, ns2__getCustomCarsInf_, ns2__getCustomCarsInfResponse_) : SOAP_EOM; };
	/// Invoke 'setGoodsStatus' of service 'FmpServiceImplServiceSoapBinding' and return error code (or SOAP_OK)
	virtual int __ns1__setGoodsStatus(ns2__setGoodsStatus *ns2__setGoodsStatus_, ns2__setGoodsStatusResponse *ns2__setGoodsStatusResponse_) { return soap ? soap_call___ns1__setGoodsStatus(soap, endpoint, NULL, ns2__setGoodsStatus_, ns2__setGoodsStatusResponse_) : SOAP_EOM; };
	/// Invoke 'delGoodsInf' of service 'FmpServiceImplServiceSoapBinding' and return error code (or SOAP_OK)
	virtual int __ns1__delGoodsInf(ns2__delGoodsInf *ns2__delGoodsInf_, ns2__delGoodsInfResponse *ns2__delGoodsInfResponse_) { return soap ? soap_call___ns1__delGoodsInf(soap, endpoint, NULL, ns2__delGoodsInf_, ns2__delGoodsInfResponse_) : SOAP_EOM; };
	/// Invoke 'getSearchGoodsInf' of service 'FmpServiceImplServiceSoapBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getSearchGoodsInf(ns2__getSearchGoodsInf *ns2__getSearchGoodsInf_, ns2__getSearchGoodsInfResponse *ns2__getSearchGoodsInfResponse_) { return soap ? soap_call___ns1__getSearchGoodsInf(soap, endpoint, NULL, ns2__getSearchGoodsInf_, ns2__getSearchGoodsInfResponse_) : SOAP_EOM; };
	/// Invoke 'getSearchGoodsInfNew' of service 'FmpServiceImplServiceSoapBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getSearchGoodsInfNew(ns2__getSearchGoodsInfNew *ns2__getSearchGoodsInfNew_, ns2__getSearchGoodsInfNewResponse *ns2__getSearchGoodsInfNewResponse_) { return soap ? soap_call___ns1__getSearchGoodsInfNew(soap, endpoint, NULL, ns2__getSearchGoodsInfNew_, ns2__getSearchGoodsInfNewResponse_) : SOAP_EOM; };
	/// Invoke 'getMyGoodsInf' of service 'FmpServiceImplServiceSoapBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getMyGoodsInf(ns2__getMyGoodsInf *ns2__getMyGoodsInf_, ns2__getMyGoodsInfResponse *ns2__getMyGoodsInfResponse_) { return soap ? soap_call___ns1__getMyGoodsInf(soap, endpoint, NULL, ns2__getMyGoodsInf_, ns2__getMyGoodsInfResponse_) : SOAP_EOM; };
	/// Invoke 'getSystemScrollAd' of service 'FmpServiceImplServiceSoapBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getSystemScrollAd(ns2__getSystemScrollAd *ns2__getSystemScrollAd_, ns2__getSystemScrollAdResponse *ns2__getSystemScrollAdResponse_) { return soap ? soap_call___ns1__getSystemScrollAd(soap, endpoint, NULL, ns2__getSystemScrollAd_, ns2__getSystemScrollAdResponse_) : SOAP_EOM; };
	/// Invoke 'getAgentScrollAd' of service 'FmpServiceImplServiceSoapBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getAgentScrollAd(ns2__getAgentScrollAd *ns2__getAgentScrollAd_, ns2__getAgentScrollAdResponse *ns2__getAgentScrollAdResponse_) { return soap ? soap_call___ns1__getAgentScrollAd(soap, endpoint, NULL, ns2__getAgentScrollAd_, ns2__getAgentScrollAdResponse_) : SOAP_EOM; };
	/// Invoke 'getCustomGoodsInf' of service 'FmpServiceImplServiceSoapBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getCustomGoodsInf(ns2__getCustomGoodsInf *ns2__getCustomGoodsInf_, ns2__getCustomGoodsInfResponse *ns2__getCustomGoodsInfResponse_) { return soap ? soap_call___ns1__getCustomGoodsInf(soap, endpoint, NULL, ns2__getCustomGoodsInf_, ns2__getCustomGoodsInfResponse_) : SOAP_EOM; };
	/// Invoke 'getClickSearchBulkGoodsInf' of service 'FmpServiceImplServiceSoapBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getClickSearchBulkGoodsInf(ns2__getClickSearchBulkGoodsInf *ns2__getClickSearchBulkGoodsInf_, ns2__getClickSearchBulkGoodsInfResponse *ns2__getClickSearchBulkGoodsInfResponse_) { return soap ? soap_call___ns1__getClickSearchBulkGoodsInf(soap, endpoint, NULL, ns2__getClickSearchBulkGoodsInf_, ns2__getClickSearchBulkGoodsInfResponse_) : SOAP_EOM; };
	/// Invoke 'checkChargeUser' of service 'FmpServiceImplServiceSoapBinding' and return error code (or SOAP_OK)
	virtual int __ns1__checkChargeUser(ns2__checkChargeUser *ns2__checkChargeUser_, ns2__checkChargeUserResponse *ns2__checkChargeUserResponse_) { return soap ? soap_call___ns1__checkChargeUser(soap, endpoint, NULL, ns2__checkChargeUser_, ns2__checkChargeUserResponse_) : SOAP_EOM; };
	/// Invoke 'deleteUserCustomInf' of service 'FmpServiceImplServiceSoapBinding' and return error code (or SOAP_OK)
	virtual int __ns1__deleteUserCustomInf(ns2__deleteUserCustomInf *ns2__deleteUserCustomInf_, ns2__deleteUserCustomInfResponse *ns2__deleteUserCustomInfResponse_) { return soap ? soap_call___ns1__deleteUserCustomInf(soap, endpoint, NULL, ns2__deleteUserCustomInf_, ns2__deleteUserCustomInfResponse_) : SOAP_EOM; };
	/// Invoke 'setServiceStationInf' of service 'FmpServiceImplServiceSoapBinding' and return error code (or SOAP_OK)
	virtual int __ns1__setServiceStationInf(ns2__setServiceStationInf *ns2__setServiceStationInf_, ns2__setServiceStationInfResponse *ns2__setServiceStationInfResponse_) { return soap ? soap_call___ns1__setServiceStationInf(soap, endpoint, NULL, ns2__setServiceStationInf_, ns2__setServiceStationInfResponse_) : SOAP_EOM; };
	/// Invoke 'getAllSpecialLineInf' of service 'FmpServiceImplServiceSoapBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getAllSpecialLineInf(ns2__getAllSpecialLineInf *ns2__getAllSpecialLineInf_, ns2__getAllSpecialLineInfResponse *ns2__getAllSpecialLineInfResponse_) { return soap ? soap_call___ns1__getAllSpecialLineInf(soap, endpoint, NULL, ns2__getAllSpecialLineInf_, ns2__getAllSpecialLineInfResponse_) : SOAP_EOM; };
	/// Invoke 'getClickSearchSpecialLineInf' of service 'FmpServiceImplServiceSoapBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getClickSearchSpecialLineInf(ns2__getClickSearchSpecialLineInf *ns2__getClickSearchSpecialLineInf_, ns2__getClickSearchSpecialLineInfResponse *ns2__getClickSearchSpecialLineInfResponse_) { return soap ? soap_call___ns1__getClickSearchSpecialLineInf(soap, endpoint, NULL, ns2__getClickSearchSpecialLineInf_, ns2__getClickSearchSpecialLineInfResponse_) : SOAP_EOM; };
	/// Invoke 'delSpecialLineInf' of service 'FmpServiceImplServiceSoapBinding' and return error code (or SOAP_OK)
	virtual int __ns1__delSpecialLineInf(ns2__delSpecialLineInf *ns2__delSpecialLineInf_, ns2__delSpecialLineInfResponse *ns2__delSpecialLineInfResponse_) { return soap ? soap_call___ns1__delSpecialLineInf(soap, endpoint, NULL, ns2__delSpecialLineInf_, ns2__delSpecialLineInfResponse_) : SOAP_EOM; };
	/// Invoke 'getMyBulkGoodsInf' of service 'FmpServiceImplServiceSoapBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getMyBulkGoodsInf(ns2__getMyBulkGoodsInf *ns2__getMyBulkGoodsInf_, ns2__getMyBulkGoodsInfResponse *ns2__getMyBulkGoodsInfResponse_) { return soap ? soap_call___ns1__getMyBulkGoodsInf(soap, endpoint, NULL, ns2__getMyBulkGoodsInf_, ns2__getMyBulkGoodsInfResponse_) : SOAP_EOM; };
	/// Invoke 'addUserCustomInf' of service 'FmpServiceImplServiceSoapBinding' and return error code (or SOAP_OK)
	virtual int __ns1__addUserCustomInf(ns2__addUserCustomInf *ns2__addUserCustomInf_, ns2__addUserCustomInfResponse *ns2__addUserCustomInfResponse_) { return soap ? soap_call___ns1__addUserCustomInf(soap, endpoint, NULL, ns2__addUserCustomInf_, ns2__addUserCustomInfResponse_) : SOAP_EOM; };
	/// Invoke 'getClickSearchGoodsInf' of service 'FmpServiceImplServiceSoapBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getClickSearchGoodsInf(ns2__getClickSearchGoodsInf *ns2__getClickSearchGoodsInf_, ns2__getClickSearchGoodsInfResponse *ns2__getClickSearchGoodsInfResponse_) { return soap ? soap_call___ns1__getClickSearchGoodsInf(soap, endpoint, NULL, ns2__getClickSearchGoodsInf_, ns2__getClickSearchGoodsInfResponse_) : SOAP_EOM; };
	/// Invoke 'setPubGoodsInf' of service 'FmpServiceImplServiceSoapBinding' and return error code (or SOAP_OK)
	virtual int __ns1__setPubGoodsInf(ns2__setPubGoodsInf *ns2__setPubGoodsInf_, ns2__setPubGoodsInfResponse *ns2__setPubGoodsInfResponse_) { return soap ? soap_call___ns1__setPubGoodsInf(soap, endpoint, NULL, ns2__setPubGoodsInf_, ns2__setPubGoodsInfResponse_) : SOAP_EOM; };
	/// Invoke 'getNewCarsInf' of service 'FmpServiceImplServiceSoapBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getNewCarsInf(ns2__getNewCarsInf *ns2__getNewCarsInf_, ns2__getNewCarsInfResponse *ns2__getNewCarsInfResponse_) { return soap ? soap_call___ns1__getNewCarsInf(soap, endpoint, NULL, ns2__getNewCarsInf_, ns2__getNewCarsInfResponse_) : SOAP_EOM; };
	/// Invoke 'getSearchBulkGoodsInf' of service 'FmpServiceImplServiceSoapBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getSearchBulkGoodsInf(ns2__getSearchBulkGoodsInf *ns2__getSearchBulkGoodsInf_, ns2__getSearchBulkGoodsInfResponse *ns2__getSearchBulkGoodsInfResponse_) { return soap ? soap_call___ns1__getSearchBulkGoodsInf(soap, endpoint, NULL, ns2__getSearchBulkGoodsInf_, ns2__getSearchBulkGoodsInfResponse_) : SOAP_EOM; };
	/// Invoke 'setPubBulkGoodsInf' of service 'FmpServiceImplServiceSoapBinding' and return error code (or SOAP_OK)
	virtual int __ns1__setPubBulkGoodsInf(ns2__setPubBulkGoodsInf *ns2__setPubBulkGoodsInf_, ns2__setPubBulkGoodsInfResponse *ns2__setPubBulkGoodsInfResponse_) { return soap ? soap_call___ns1__setPubBulkGoodsInf(soap, endpoint, NULL, ns2__setPubBulkGoodsInf_, ns2__setPubBulkGoodsInfResponse_) : SOAP_EOM; };
	/// Invoke 'setPubCarsInf' of service 'FmpServiceImplServiceSoapBinding' and return error code (or SOAP_OK)
	virtual int __ns1__setPubCarsInf(ns2__setPubCarsInf *ns2__setPubCarsInf_, ns2__setPubCarsInfResponse *ns2__setPubCarsInfResponse_) { return soap ? soap_call___ns1__setPubCarsInf(soap, endpoint, NULL, ns2__setPubCarsInf_, ns2__setPubCarsInfResponse_) : SOAP_EOM; };
	/// Invoke 'getClickSearchCarsInf' of service 'FmpServiceImplServiceSoapBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getClickSearchCarsInf(ns2__getClickSearchCarsInf *ns2__getClickSearchCarsInf_, ns2__getClickSearchCarsInfResponse *ns2__getClickSearchCarsInfResponse_) { return soap ? soap_call___ns1__getClickSearchCarsInf(soap, endpoint, NULL, ns2__getClickSearchCarsInf_, ns2__getClickSearchCarsInfResponse_) : SOAP_EOM; };
	/// Invoke 'delBulkGoodsInf' of service 'FmpServiceImplServiceSoapBinding' and return error code (or SOAP_OK)
	virtual int __ns1__delBulkGoodsInf(ns2__delBulkGoodsInf *ns2__delBulkGoodsInf_, ns2__delBulkGoodsInfResponse *ns2__delBulkGoodsInfResponse_) { return soap ? soap_call___ns1__delBulkGoodsInf(soap, endpoint, NULL, ns2__delBulkGoodsInf_, ns2__delBulkGoodsInfResponse_) : SOAP_EOM; };
	/// Invoke 'usrLogin' of service 'FmpServiceImplServiceSoapBinding' and return error code (or SOAP_OK)
	virtual int __ns1__usrLogin(ns2__usrLogin *ns2__usrLogin_, ns2__usrLoginResponse *ns2__usrLoginResponse_) { return soap ? soap_call___ns1__usrLogin(soap, endpoint, NULL, ns2__usrLogin_, ns2__usrLoginResponse_) : SOAP_EOM; };
	/// Invoke 'getPersisGoodsInfo' of service 'FmpServiceImplServiceSoapBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getPersisGoodsInfo(ns2__getPersisGoodsInfo *ns2__getPersisGoodsInfo_, ns2__getPersisGoodsInfoResponse *ns2__getPersisGoodsInfoResponse_) { return soap ? soap_call___ns1__getPersisGoodsInfo(soap, endpoint, NULL, ns2__getPersisGoodsInfo_, ns2__getPersisGoodsInfoResponse_) : SOAP_EOM; };
	/// Invoke 'browseZoneCars' of service 'FmpServiceImplServiceSoapBinding' and return error code (or SOAP_OK)
	virtual int __ns1__browseZoneCars(ns2__browseZoneCars *ns2__browseZoneCars_, ns2__browseZoneCarsResponse *ns2__browseZoneCarsResponse_) { return soap ? soap_call___ns1__browseZoneCars(soap, endpoint, NULL, ns2__browseZoneCars_, ns2__browseZoneCarsResponse_) : SOAP_EOM; };
	/// Invoke 'placeOrder' of service 'FmpServiceImplServiceSoapBinding' and return error code (or SOAP_OK)
	virtual int __ns1__placeOrder(ns2__placeOrder *ns2__placeOrder_, ns2__placeOrderResponse *ns2__placeOrderResponse_) { return soap ? soap_call___ns1__placeOrder(soap, endpoint, NULL, ns2__placeOrder_, ns2__placeOrderResponse_) : SOAP_EOM; };
	/// Invoke 'getPersisCarsInfo' of service 'FmpServiceImplServiceSoapBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getPersisCarsInfo(ns2__getPersisCarsInfo *ns2__getPersisCarsInfo_, ns2__getPersisCarsInfoResponse *ns2__getPersisCarsInfoResponse_) { return soap ? soap_call___ns1__getPersisCarsInfo(soap, endpoint, NULL, ns2__getPersisCarsInfo_, ns2__getPersisCarsInfoResponse_) : SOAP_EOM; };
	/// Invoke 'delCarsInf' of service 'FmpServiceImplServiceSoapBinding' and return error code (or SOAP_OK)
	virtual int __ns1__delCarsInf(ns2__delCarsInf *ns2__delCarsInf_, ns2__delCarsInfResponse *ns2__delCarsInfResponse_) { return soap ? soap_call___ns1__delCarsInf(soap, endpoint, NULL, ns2__delCarsInf_, ns2__delCarsInfResponse_) : SOAP_EOM; };
	/// Invoke 'getMySpecialLineInf' of service 'FmpServiceImplServiceSoapBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getMySpecialLineInf(ns2__getMySpecialLineInf *ns2__getMySpecialLineInf_, ns2__getMySpecialLineInfResponse *ns2__getMySpecialLineInfResponse_) { return soap ? soap_call___ns1__getMySpecialLineInf(soap, endpoint, NULL, ns2__getMySpecialLineInf_, ns2__getMySpecialLineInfResponse_) : SOAP_EOM; };
	/// Invoke 'setPubSpecialLineInf' of service 'FmpServiceImplServiceSoapBinding' and return error code (or SOAP_OK)
	virtual int __ns1__setPubSpecialLineInf(ns2__setPubSpecialLineInf *ns2__setPubSpecialLineInf_, ns2__setPubSpecialLineInfResponse *ns2__setPubSpecialLineInfResponse_) { return soap ? soap_call___ns1__setPubSpecialLineInf(soap, endpoint, NULL, ns2__setPubSpecialLineInf_, ns2__setPubSpecialLineInfResponse_) : SOAP_EOM; };
	/// Invoke 'getNewGoodsInf' of service 'FmpServiceImplServiceSoapBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getNewGoodsInf(ns2__getNewGoodsInf *ns2__getNewGoodsInf_, ns2__getNewGoodsInfResponse *ns2__getNewGoodsInfResponse_) { return soap ? soap_call___ns1__getNewGoodsInf(soap, endpoint, NULL, ns2__getNewGoodsInf_, ns2__getNewGoodsInfResponse_) : SOAP_EOM; };
	/// Invoke 'delFavoriteSpecialLine' of service 'FmpServiceImplServiceSoapBinding' and return error code (or SOAP_OK)
	virtual int __ns1__delFavoriteSpecialLine(ns2__delFavoriteSpecialLine *ns2__delFavoriteSpecialLine_, ns2__delFavoriteSpecialLineResponse *ns2__delFavoriteSpecialLineResponse_) { return soap ? soap_call___ns1__delFavoriteSpecialLine(soap, endpoint, NULL, ns2__delFavoriteSpecialLine_, ns2__delFavoriteSpecialLineResponse_) : SOAP_EOM; };
	/// Invoke 'getSearchCarsInfNew' of service 'FmpServiceImplServiceSoapBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getSearchCarsInfNew(ns2__getSearchCarsInfNew *ns2__getSearchCarsInfNew_, ns2__getSearchCarsInfNewResponse *ns2__getSearchCarsInfNewResponse_) { return soap ? soap_call___ns1__getSearchCarsInfNew(soap, endpoint, NULL, ns2__getSearchCarsInfNew_, ns2__getSearchCarsInfNewResponse_) : SOAP_EOM; };
	/// Invoke 'getAgentPopAd' of service 'FmpServiceImplServiceSoapBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getAgentPopAd(ns2__getAgentPopAd *ns2__getAgentPopAd_, ns2__getAgentPopAdResponse *ns2__getAgentPopAdResponse_) { return soap ? soap_call___ns1__getAgentPopAd(soap, endpoint, NULL, ns2__getAgentPopAd_, ns2__getAgentPopAdResponse_) : SOAP_EOM; };
	/// Invoke 'getSearchCarsInf' of service 'FmpServiceImplServiceSoapBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getSearchCarsInf(ns2__getSearchCarsInf *ns2__getSearchCarsInf_, ns2__getSearchCarsInfResponse *ns2__getSearchCarsInfResponse_) { return soap ? soap_call___ns1__getSearchCarsInf(soap, endpoint, NULL, ns2__getSearchCarsInf_, ns2__getSearchCarsInfResponse_) : SOAP_EOM; };
};
#endif
